server:
  port: 8888
spring:
  application:
    name: account-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: a56a2d09-133d-44b5-b72d-2d876ce9767a
    alibaba:
      seata:
        tx-service-group: my_test_tx_group